version: 2
jobs:
  test:
    docker:
      - image: circleci/golang:1.9
    working_directory: /go/src/github.com/bryutus/kivu
    steps:
      - checkout
      - run: go get -v -t -d ./...
      - run: go test -cover -v ./...
  deploy:
    docker:
      - image: circleci/golang:1.9
    working_directory: /go/src/github.com/bryutus/kivu
    steps:
      - checkout
      - run: go get -v -t -d ./...
      - run: go get github.com/mitchellh/gox
      - run: go get github.com/tcnksm/ghr
      - run: gox -os="linux darwin windows" -arch="386 amd64" -output "dist/{{.Dir}}_{{.OS}}_{{.Arch}}"
      - run: ghr -t ${GITHUB_TOKEN} -u ${USERNAME} -r ${CIRCLE_PROJECT_REPONAME} --replace `cat release_tag` dist/
workflows:
  version: 2
  test_and_deploy:
    jobs:
      - test:
          filters:
            branches:
              only: /.*/
            tags:
              only: /.*/
      - deploy:
          requires:
            - test
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /v[0-9]+(\.[0-9]+)*/
